# REMEMBER TO GO THROUGH THIS FILE, PERSONALISING THE SETTINGS
title: Rautalanka
author:
  name: Sami Singh
  github: httpsterio
  twitter: httpsterio

twitter: httpsterio

# If you don't have a favicon, change to false.
favicon: true

footer:
  separator: '|'
  content: Ⓒ Sami Singh
  # Append current year on build
  year: true

baseurl: "" # Use if your site will be located in a subdirectory, e.g. /blog.
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: Rautalanka on suomenkielinen blogi ja podcast suunnittelusta, suunnittelijoille.

# Build settings
theme: rautalanka
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Enable theme compononents
enabled:
  breadcrumbs: false
  tags: true
  tag-cloud: false
  comments: false
  # Enable RSS menu item
  rss: false
  seo: true

  logo: assets/images/logo.svg

# Get your disqus shortname from the disqus admin panel for your blog.
## disqus_shortname: your-forum-shortname
# Define the colors for social buttons.
## socialBtnsColor: '#4845DF'
lang: fi
#Plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate

# Compress Sass for production.
sass:
  style: compressed

# Specifying front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      author: "Sami Singh"
      comments: false

# Permalink formating, omits file extension
permalink: pretty

# Archives
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: 'archive'
  layouts:
    tag: 'tag_page'
    month: month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# How many posts per page
paginate: 5

# How long post previews are before truncating
truncation: 40

# Adds borders around all elements and all focusable elements
debugscss: false

# Exclude files and folders from being built into _site
exclude: [node_modules, gulpfile.js, rautalanka.gemspec, rautalanka-0.1.gem, package.json, doc, Gemfile.lock, Gemfile, changelog.md, .gitignore, README.md]
